apiVersion: apps/v1
kind: Deployment
metadata:
  name: spot
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spot
  template:
    metadata:
      labels:
        app: spot
    spec:
      containers:
      - name: spot
        image: acralacancha.azurecr.io/spot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: DB_HOST
          value: "alacancha.postgres.database.azure.com"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "alacancha"
        - name: DB_USER
          value: "servicio_spot"
        - name: DB_SSL
          value: "true"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: DB_PASSWORD